config/routes.rb
Rock::Application.routes.draw do
  devise_for :users

  devise_scope :user do
    get "sign-in", to: "devise/sessions#new"
  end

  namespace :admin do
    resources :categories
    resources :products
    resources :sliders
    resources :feedbacks, only: [:index, :show, :destroy]
  end

  resources :home_pages, only: [:index]

  resources :categories, only: [:index] do
    resources :products, only: [:index]
  end

  resources :feedbacks, only: [:index, :new, :create]

  root :to => 'home_pages#index'

end

app/models/slider.rb
class Slider < ActiveRecord::Base
  AMOUNT = 5

  attr_accessible :image

  has_attached_file :image, url: '/images/:class/:attachment/:id/:style/:filename',
                            path: ':rails_root/public/images/:class/:attachment/:id/:style/:filename'

  validates_attachment :image, presence: true,
                               content_type: { content_type: %w(image/jpeg image/jpg image/png image/gif) },
                               size: { in: 0..10.megabytes }
  validate :image_dimensions


private

  def image_dimensions
    temp_file = image.queued_for_write[:original]
    unless temp_file.nil?
      dimensions = Paperclip::Geometry.from_file(temp_file)
      errors.add(:image, 'Dimension should be 770x400 px')  if dimensions.width != 770 && dimensions.height != 400
    end
  end
end

app/controllers/admin/sliders_controller.rb
class Admin::SlidersController < Admin::BaseController
  load_and_authorize_resource

  def index
    @sliders = Slider.all
  end

  def new
  end

  def create
    if @slider.save
      flash[:notice] = "Successfully created slider"
      redirect_to [:admin, @slider]
    else
      render :new
    end
  end

  def edit
  end

  def update
    if @slider.update_attributes params[:slider]
      flash[:notice] = "Successfully updated slider"
      redirect_to [:admin, @slider]
    else
      render :edit
    end
  end

  def destroy
    @slider.destroy
    flash[:notice] = "Slider was successfully deleted"
    redirect_to admin_sliders_path
  end
end

app/helpers/admin/sliders_helper.rb
module Admin::SlidersHelper
end

app/views/admin/sliders/_form.html.haml
= simple_form_for [:admin, @slider], html: { class: 'form-horizontal' } do |f|
  %fieldset
    %legend= "#{controller.action_name.capitalize} Slider"

    = f.input :image, as: :file

    .form-actions
      = f.submit nil, class: 'btn btn-primary'
      = link_to 'Cancel', admin_sliders_path, class: 'btn'

app/views/admin/sliders/edit.html.haml
= render 'form'

app/views/admin/sliders/index.html.haml
%h1 Sliders
= link_to 'New', new_admin_slider_path, class: 'btn btn-primary' if @sliders.count < Slider::AMOUNT
.row-fluid
  %br
  - if @sliders.present?
    %ul#sliders.thumbnails
      - @sliders.each do |slider|
        %li.span4.pull-left
          .thumbnail
            = link_to image_tag(slider.image.url), admin_slider_path(slider)
            .caption
              %p.text-center
                = link_to 'Edit', edit_admin_slider_path(slider), class: 'btn btn-primary'
                = link_to 'Destroy', admin_slider_path(slider), method: :delete, confirm: 'Are you sure?', class: 'btn btn-danger'
  - else
    .well.text-center No Sliders were created yet.

app/views/admin/sliders/new.html.haml
= render 'form'

app/views/admin/sliders/show.html.haml
%h1 Slider

- if @slider.image.exists?
  %p
    %b Image
    %br
  = image_tag @slider.image.url

.form-actions
  = link_to 'Back', admin_sliders_path, class: 'btn'
  = link_to 'Edit', edit_admin_slider_path(@slider), class: 'btn'
  = link_to 'Delete', admin_slider_path(@slider), method: 'delete', confirm: 'Are you sure?', class: 'btn btn-danger'