config/routes.rb
Rock::Application.routes.draw do
  devise_for :users

  devise_scope :user do
    get "sign-in", to: "devise/sessions#new"
  end

  namespace :admin do
    resources :categories
    resources :products
    resources :sliders
    resources :feedbacks, only: [:index, :show, :destroy]
  end

  resources :home_pages, only: [:index]

  resources :categories, only: [:index] do
    resources :products, only: [:index]
  end

  resources :feedbacks, only: [:index, :new, :create]

  root :to => 'home_pages#index'

end

app/models/product.rb
class Product < ActiveRecord::Base
  RECENT_LIMIT = 12

  attr_accessible :description, :title, :category_id, :image

  belongs_to :category

  delegate :name, to: :category, prefix: true, allow_nil: true

  has_attached_file :image, styles: { small: '120x87#', medium: '270x180#' },
                            url: '/images/:class/:attachment/:id/:style/:filename',
                            path: ':rails_root/public/images/:class/:attachment/:id/:style/:filename'

  validates :category, presence: true
  validates_attachment :image, presence: true,
                               content_type: { content_type: %w(image/jpeg image/jpg image/png image/gif) },
                               size: { in: 0..10.megabytes }

  scope :recent, -> { order('updated_at desc').limit(RECENT_LIMIT) }

  def self.filter_by_category(category_id)
    return all if category_id.blank?
    joins(:category).where(categories: { id: category_id })
  end
end

app/controllers/admin/products_controller.rb
class Admin::ProductsController < Admin::BaseController
  load_and_authorize_resource

  def index
    @products = Product.filter_by_category(params[:category_id])
  end

  def new
  end

  def create
    if @product.save
      flash[:notice] = "Successfully created product"
      redirect_to [:admin, @product]
    else
      render :new
    end
  end

  def edit
  end

  def update
    if @product.update_attributes params[:product]
      flash[:notice] = "Succeallssfully updated product"
      redirect_to [:admin, @product]
    else
      render :edit
    end
  end

  def destroy
    @product.destroy
    flash[:notice] = "Product was successfully deleted"
    redirect_to admin_products_path
  end
end

app/controllers/products_controller.rb
class ProductsController < ApplicationController
  def index
    @category = Category.find(params[:category_id])
    @products = @category.products
  end
end

app/helpers/admin/products_helper.rb
module Admin::ProductsHelper
end

app/helpers/products_helper.rb
module ProductsHelper
end

app/views/admin/products/_form.html.haml
= simple_form_for [:admin, @product], :html => { :class => 'form-horizontal' } do |f|
  %fieldset
    %legend= "#{controller.action_name.capitalize} Product"

    = f.input :title
    = f.association :category
    = f.input :description, as: :text
    = f.input :image, as: :file

    .form-actions
      = f.submit nil, class: 'btn btn-primary'
      = link_to 'Cancel', admin_products_path, class: 'btn'

app/views/admin/products/edit.html.haml
= render partial: 'form'

app/views/admin/products/index.html.haml
%h1 Products
.row
  .span4
    = link_to 'New', new_admin_product_path, class: 'btn btn-primary'
  .span8
    = form_tag admin_products_path, method: :get, class: 'form-inline pull-right', id: 'category-filter' do
      = select_tag :category_id, options_from_collection_for_select(Category.all, :id, :name, params[:category_id]), prompt: "All Categories", class: 'span3'
- if @products.present?
  %table.table.table-striped
    %thead
      %tr
        %th Title
        %th Category
    %tbody
      - @products.each do |product|
        %tr
          %td= link_to product.title, admin_product_path(product)
          %td= product.category_name
          %td
            = link_to 'Show', admin_product_path(product), class: 'btn btn-mini'
            = link_to 'Edit', edit_admin_product_path(product), class: 'btn btn-mini'
            = link_to 'Destroy', admin_product_path(product), method: :delete, confirm: 'Are you sure?', class: 'btn btn-mini btn-danger'
- else
  .well.text-center No Products were created yet.

app/views/admin/products/new.html.haml
= render partial: 'form'

app/views/admin/products/show.html.haml
%h1 Product

%p
  %b Title
  %br
  = @product.title

%p
  %b Category
  %br
  = @product.category.name

%p
  %b Description
  %br
  = @product.description

- if @product.image.exists?
  %p
    %b Image
    %br
  = image_tag @product.image.url

.form-actions
  = link_to 'Back', admin_products_path, class: 'btn'
  = link_to 'Edit', edit_admin_product_path(@product), class: 'btn'
  = link_to 'Delete', admin_product_path(@product), method: 'delete', confirm: 'Are you sure?', class: 'btn btn-danger'