config/routes.rb
Rock::Application.routes.draw do
  devise_for :users

  devise_scope :user do
    get "sign-in", to: "devise/sessions#new"
  end

  namespace :admin do
    resources :categories
    resources :products
    resources :sliders
    resources :feedbacks, only: [:index, :show, :destroy]
  end

  resources :home_pages, only: [:index]

  resources :categories, only: [:index] do
    resources :products, only: [:index]
  end

  resources :feedbacks, only: [:index, :new, :create]

  root :to => 'home_pages#index'

end

app/models/ability.rb
class Ability
  include CanCan::Ability

  def initialize(user)
    # Define abilities for the passed in user here. For example:
    #
    user ||= User.new # guest user (not logged in)
    if user.admin?
      can :manage, :all
    else
      can :read, :all
    end
    #
    # The first argument to `can` is the action you are giving the user
    # permission to do.
    # If you pass :manage it will apply to every action. Other common actions
    # here are :read, :create, :update and :destroy.
    #
    # The second argument is the resource the user can perform the action on.
    # If you pass :all it will apply to every resource. Otherwise pass a Ruby
    # class of the resource.
    #
    # The third argument is an optional hash of conditions to further filter the
    # objects.
    # For example, here the user can only update published articles.
    #
    #   can :update, Article, :published => true
    #
    # See the wiki for details:
    # https://github.com/ryanb/cancan/wiki/Defining-Abilities
  end
end

app/models/category.rb
class Category < ActiveRecord::Base
  attr_accessible :description, :name, :image, :title

  has_many :products

  has_attached_file :image, styles: { small: '270x146#' },
                            url: '/images/:class/:attachment/:id/:style/:filename',
                            path: ':rails_root/public/images/:class/:attachment/:id/:style/:filename'


  validates :name, :description, :title, presence: true
  validates_attachment :image, presence: true,
                               content_type: { content_type: %w(image/jpeg image/jpg image/png image/gif) },
                               size: { in: 0..10.megabytes }
  validate :image_dimensions

  scope :with_products, -> { includes(:products).where('products.id IS NOT NULL') }

private

  def image_dimensions
    temp_file = image.queued_for_write[:original]
    unless temp_file.nil?
      dimensions = Paperclip::Geometry.from_file(temp_file)
      errors.add(:image, 'Dimension should be 350x350 px')  if dimensions.width != 350 && dimensions.height != 350
    end
  end
end

app/models/feedback.rb
class Feedback < ActiveRecord::Base
  attr_accessible :email, :message, :name, :phone

  validates :message, :name, :phone, :email, presence: true
  validates :email, format: { with: Devise.email_regexp }, if: -> { email.present? }

  scope :already_seen, ->(boolean=false) { where(watched: boolean) }
end

app/models/product.rb
class Product < ActiveRecord::Base
  RECENT_LIMIT = 12

  attr_accessible :description, :title, :category_id, :image

  belongs_to :category

  delegate :name, to: :category, prefix: true, allow_nil: true

  has_attached_file :image, styles: { small: '120x87#', medium: '270x180#' },
                            url: '/images/:class/:attachment/:id/:style/:filename',
                            path: ':rails_root/public/images/:class/:attachment/:id/:style/:filename'

  validates :category, presence: true
  validates_attachment :image, presence: true,
                               content_type: { content_type: %w(image/jpeg image/jpg image/png image/gif) },
                               size: { in: 0..10.megabytes }

  scope :recent, -> { order('updated_at desc').limit(RECENT_LIMIT) }

  def self.filter_by_category(category_id)
    return all if category_id.blank?
    joins(:category).where(categories: { id: category_id })
  end
end

app/models/slider.rb
class Slider < ActiveRecord::Base
  AMOUNT = 5

  attr_accessible :image

  has_attached_file :image, url: '/images/:class/:attachment/:id/:style/:filename',
                            path: ':rails_root/public/images/:class/:attachment/:id/:style/:filename'

  validates_attachment :image, presence: true,
                               content_type: { content_type: %w(image/jpeg image/jpg image/png image/gif) },
                               size: { in: 0..10.megabytes }
  validate :image_dimensions


private

  def image_dimensions
    temp_file = image.queued_for_write[:original]
    unless temp_file.nil?
      dimensions = Paperclip::Geometry.from_file(temp_file)
      errors.add(:image, 'Dimension should be 770x400 px')  if dimensions.width != 770 && dimensions.height != 400
    end
  end
end

app/models/user.rb
class User < ActiveRecord::Base
  devise :database_authenticatable, :trackable, :validatable, :rememberable

  attr_accessible :email, :password, :password_confirmation, :first_name, :last_name

  validates :first_name, :last_name, presence: true

  def name
    "#{first_name} #{last_name}"
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery

  before_filter :load_categories

private
  def load_categories
    @categories = Category.with_products
  end
end

app/controllers/categories_controller.rb
class CategoriesController < ApplicationController
  def index
    # @categories = Category.with_products
  end
end

app/controllers/feedbacks_controller.rb
class FeedbacksController < ApplicationController
  def index
    @feedback = Feedback.new
  end

  def new
    @feedback = Feedback.new
  end

  def create
    @feedback = Feedback.new(params[:feedback])
    if @feedback.save
      render :create
    else
      render :new
    end
  end
end

app/controllers/home_pages_controller.rb
class HomePagesController < ApplicationController
  def index
    @sliders = Slider.all
    @recent_products = Product.recent
  end
end

app/controllers/products_controller.rb
class ProductsController < ApplicationController
  def index
    @category = Category.find(params[:category_id])
    @products = @category.products
  end
end

app/helpers/admin/categories_helper.rb
module Admin::CategoriesHelper
end

app/helpers/admin/feedbacks_helper.rb
module Admin::FeedbacksHelper
end

app/helpers/admin/products_helper.rb
module Admin::ProductsHelper
end

app/helpers/admin/sliders_helper.rb
module Admin::SlidersHelper
end

app/helpers/application_helper.rb
module ApplicationHelper
  def navigation_link(link_text, link_path, options={}, &block)
    parent_class = current_page?(link_path) ? 'active' : ''
    nested_html = ''

    if block_given?
      nested_html = content_tag(:ul) do
                      yield.collect do |resource|
                        path = url_for([resource, options[:resource]])
                        parent_class = 'active' if current_page?(path)
                        nested_class = current_page?(path) ? 'active' : ''
                        content_tag(:li, link_to(resource.name, path), class: nested_class)
                      end.join.html_safe
                    end
      parent_class.concat(' sub-menu')
    end

    content_tag(:li, link_to(link_text, link_path).concat(nested_html), class: parent_class).html_safe
  end
end

app/helpers/categories_helper.rb
module CategoriesHelper
end

app/helpers/feedbacks_helper.rb
module FeedbacksHelper
end

app/helpers/home_pages_helper.rb
module HomePagesHelper
end

app/helpers/products_helper.rb
module ProductsHelper
end

app/views/layouts/admin.html.haml
!!! 5
%html(lang="en")
  %head
    %meta(charset="utf-8")
    %meta(http-equiv="X-UA-Compatible" content="IE=Edge,chrome=1")
    %meta(name="viewport" content="width=device-width, initial-scale=1.0")
    %title= content_for?(:title) ? yield(:title) : "Rock"
    = csrf_meta_tags
    / Le HTML5 shim, for IE6-8 support of HTML elements
    /[if lt IE 9]
      = javascript_include_tag "//cdnjs.cloudflare.com/ajax/libs/html5shiv/3.6.1/html5shiv.js"
    = stylesheet_link_tag "admin", :media => "all"
    = favicon_link_tag 'apple-touch-icon-144x144-precomposed.png', :rel => 'apple-touch-icon-precomposed', :type => 'image/png', :sizes => '144x144'
    = favicon_link_tag 'apple-touch-icon-114x114-precomposed.png', :rel => 'apple-touch-icon-precomposed', :type => 'image/png', :sizes => '114x114'
    = favicon_link_tag 'apple-touch-icon-72x72-precomposed.png', :rel => 'apple-touch-icon-precomposed', :type => 'image/png', :sizes => '72x72'
    = favicon_link_tag 'apple-touch-icon-precomposed.png', :rel => 'apple-touch-icon-precomposed', :type => 'image/png'
    = favicon_link_tag 'favicon.ico', :rel => 'shortcut icon'
    = javascript_include_tag "admin"


  %body
    .navbar.navbar-fluid-top.navbar-inverse
      .navbar-inner
        .container-fluid
          %a.btn.btn-navbar(data-target=".nav-collapse" data-toggle="collapse")
            %span.icon-bar
            %span.icon-bar
            %span.icon-bar
          = link_to 'Rock', root_path, class: 'brand'
          .container.nav-collapse
            %ul.nav
              %li= link_to "Categories", admin_categories_path
              %li= link_to "Products", admin_products_path
              %li= link_to "Slides", admin_sliders_path
              %li= link_to "Feedbacks", admin_feedbacks_path
            %ul.nav.pull-right
              - if current_user
                %li
                  .nav.navbar-text
                    .text-success= "Logged in as: #{current_user.name}"
                %li= link_to "Log Out", destroy_user_session_path, method: :delete

    .container
      - if flash[:notice]
        .alert.alert-info
          = flash[:notice]
      - if flash[:alert]
        .alert.alert-error
          = flash[:alert]
      = yield

app/views/layouts/application.html.haml
!!!
%html{lang: I18n.locale}
  %head
    %meta(charset="utf-8")
    %meta(http-equiv="X-UA-Compatible" content="IE=Edge,chrome=1")
    %meta(name="viewport" content="width=device-width, initial-scale=1.0")
    %title= content_for?(:title) ? yield(:title) : "Rock"
    = csrf_meta_tags
    = stylesheet_link_tag "application", :media => "all"
    = javascript_include_tag "application"
    = yield :head
    = favicon_link_tag 'favicon.ico', :rel => 'shortcut icon'
    %meta{content: "Your description", name: "description"}
    %meta{content: "Your keywords", name: "keywords"}
    %meta{content: "Your name", name: "author"}
    %link{href: "http://fonts.googleapis.com/css?family=Open+Sans:400,300", rel: "stylesheet", type: "text/css"}
    /[if lt IE 8]
      <div style='text-align:center'><a href="http://www.microsoft.com/windows/internet-explorer/default.aspx?ocid=ie6_countdown_bannercode"><img src="http://www.theie6countdown.com/assets/upgrade.jpg"border="0"alt=""/></a></div>
    /[if lt IE 9]
      <script src="http://html5shim.googlecode.com/svn/trunk/html5.js"></script>
      <link rel="stylesheet" href="ie.css" type="text/css" media="screen">
      <link href='http://fonts.googleapis.com/css?family=Open+Sans:300' rel='stylesheet' type='text/css'>
      <link href='http://fonts.googleapis.com/css?family=Open+Sans:400' rel='stylesheet' type='text/css'>

  %body
    .spinner
    %header
      .container.clearfix
        .row
          .span12
            .navbar.navbar_
              .container
                %h1.brand.brand_
                  = link_to image_tag('logo.png'), root_path
                %a.btn.btn-navbar.btn-navbar_{"data-target" => ".nav-collapse_", "data-toggle" => "collapse"}
                  Menu
                  %span.icon-bar
                = render 'shared/navigation'
    .bg-content
      = yield
    %footer
      .container.clearfix
        %ul.list-social.pull-right
          %li
            %a.icon-1{href: "#"}
          %li
            %a.icon-2{href: "#"}
          %li
            %a.icon-3{href: "https://twitter.com/oswt"}
          %li
            %a.icon-4{href: "#"}
        .privacy.pull-left
          Website Template designed by
          %a{href: "http://store.templatemonster.com?aff=awdawd", rel: "nofollow", target: "_blank"} TemplateMonster.com
          = succeed "Popular" do
            %br/
          %a{href: "http://www.oswt.co.uk", target: "_blank"} at www.Oswt.co.uk

app/views/shared/_navigation.html.haml
.nav-collapse.nav-collapse_.collapse
  %ul.nav.sf-menu
    = navigation_link t('.main'), root_path
    = navigation_link t('.services'), '#'
    = navigation_link t('.categories'), categories_path, resource: :products do
      - @categories
    = navigation_link t('.contact'), feedbacks_path